name: Merge Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  merge-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check for required tag
        run: |
          if ! git log -1 --pretty=%B | grep -q "ready-to-review"; then
            echo "::error::Pull request must be labeled with 'ready-to-review' to be merged"
            exit 1
          fi
