name: Merge Check

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  merge-check:
    runs-on: ubuntu-latest

    steps:
      - name: PR Labels
        run: |
          echo "Labels:"
          echo "${{ toJson(github.event.pull_request.labels) }}"
      - name: Check for "ready-to-review" label
        if: contains(github.event.pull_request.labels.*.name, 'ready-to-review')
        run: |
          echo "Ready to review label is present"
          exit 0
      - name: Fail if "ready-to-review" label is missing
        run: |
          echo "Error: Ready to review label is missing"
          exit 1
